---
- name: get current user
  command: whoami
  register: current_user
  changed_when: current_user.rc != 0
  check_mode: no
  tags:
    - shell

- name: ensure directories exist for current user
  file:
    path: "/home/{{ current_user.stdout }}/{{ item }}"
    state: directory
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0700
  with_items:
    - .docker
    - .ssh
    - bin
    - tmp
  when:
    - not current_user.stdout is search('root')
  tags:
    - shell

- name: add docker config for current user
  copy:
    src: ".docker/{{ item }}"
    dest: "/home/{{ current_user.stdout }}/.docker/{{ item }}"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0640
  with_items:
    - config.json
  when:
    - not current_user.stdout is search('root')
  tags:
    - shell

- name: add ssh config for current user
  copy:
    src: ".ssh/{{ item }}"
    dest: "/home/{{ current_user.stdout }}/.ssh/{{ item }}"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0600
  with_items:
    - config
  when:
    - not current_user.stdout is search('root')
  tags:
    - shell

- name: add dotfiles for current user
  copy:
    src: "{{ item }}"
    dest: "/home/{{ current_user.stdout }}/{{ item }}"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0640
  with_items:
    - .bash_profile
    - .bash_prompt
    - .bashrc
    - .exports
    - .gitignore_global
    - .inputrc
    - .path
  when:
    - not current_user.stdout is search('root')
  tags:
    - shell
