---
# - name: remove references to ipv6 in /etc/hosts
#   replace:
#     dest: /etc/hosts
#     regexp: '^(::1)(\s+.*)?$'
#     replace: '#\1\2'
#     backup: yes
#   tags:
#     - firewall
#     - ipv6

- name: install iptables services
  yum:
    name: iptables-services
    state: present
  tags:
    - firewall
    - yum

- name: copy iptables template
  template:
    src: iptables.j2
    dest: "{{ v_firewall_config }}"
    owner: 0
    group: 0
    mode: 0700
  notify:
    - restart iptables
  tags:
    - firewall

- name: uninstall firewalld services
  yum:
    name: firewalld
    state: absent
  ignore_errors: yes
  tags:
    - firewall
    - yum

- name: enable iptables
  service:
    name: iptables
    enabled: yes
    state: started
  tags:
    - firewall
