---
- name: sshd configuration file update
  template:
    src: sshd_config.j2
    dest: "{{ v_ssh_config }}"
    backup: yes
    owner: 0
    group: 0
    mode: 0644
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - find ssh server keys
    - delete ssh server keys
    - restart ssh
  tags:
    - ssh
