---
traefik_version: v2.3
traefik_directory: /opt/traefik

# General settings
traefik_domain: "trampfox.eu"
traefik_log_level: "WARNING"
traefik_accesslog_enable: false

# Main configuration
traefik_global_https_redirect: true
traefik_port_http: 80
traefik_port_https: 443

# Dashboard
traefik_dashboard_enable: true
traefik_dashboard_port: 8080
traefik_dashboard_subdomain: "traefik"
traefik_dashboard_basicauth_enable: true
traefik_dashboard_basicauth_users: []

# Docker
traefik_docker_enable: true
traefik_docker_network: "traefik"
traefik_docker_expose_by_default: false

# Enable automatic certificates from Let's Encrypt
traefik_acme_enable: true
traefik_acme_email: "trampfox@gmail.com"
traefik_acme_cloudflare_email: trampfox@gmail.com