---
- hosts: all
  become: yes
  gather_facts: yes

  # vars_files:
  #   - ../vars/private/users.yaml

  roles:
    - role: chrony
      tags: install
    - role: docker-engine
      tags: install
    - role: locale
      tags: install
    - role: traefik
      tags: install

# - hosts: all
#   become: yes
#   become_user: trampfox
#   gather_facts: no

#   roles:
#     - shell
