---
# Enable and allow everything
- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow all incoming SSH 
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '22'

- name: Allow all incoming HTTPS 
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '443'

# ufw will deny connections if an IP address has attempted 
# to initiate 6 or more connections in the last 30 seconds.
- name: SSH connection rate limiting
  community.general.ufw:
    rule: limit
    port: '22'
    proto: tcp

- name: HTTPS connection rate limiting
  community.general.ufw:
    rule: limit
    port: '443'
    proto: tcp

# TODO allow 443 only from cloudflare 